name: Pre-PR Lint Check

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  lint-and-format:
    name: Run Linting, Services, and Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Make start script executable
        run: chmod +x .devcontainer/start.sh

      - name: Start local services via start.sh (includes install + migrations)
        env:
          WORKSPACE_ROOT: ${{ github.workspace }}
        run: |
          bash .devcontainer/start.sh

      - name: Run linting + type checking
        run: bun format

      - name: Run API tests
        run: |
          cd packages/api
          bun test

      - name: Teardown services
        if: always()
        run: |
          docker compose -f .devcontainer/docker-compose.yml down -v
